version: '3.8'
services:
  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - ./frontend/:/app
      - /app/node_modules
    ports:
      - "3000:3000"
  back:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - ./backend/:/app
      - /app/node_modules
    ports:
      - "8080:8080"
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"
volumes:
    mongodb:
    node_modules:
    web-root:
      driver: local